import { Customer, Job, Material, Machine, Payment } from '@/types';

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    customerCode: 'CUST-1001',
    name: 'Kasun Jayawardena',
    companyName: 'Apex Robotics Sri Lanka',
    email: 'kasun@apexrobotics.lk',
    phone: '+94 77 123 4567',
    address: 'No 45, Kandy Road, Malabe',
    notes: 'Key client for drone enclosure prototypes. Prefers PETG or ASA.',
    totalJobsCount: 8,
    totalSpentLKR: 185000,
    createdAt: '2026-01-10T08:30:00Z',
    updatedAt: '2026-08-01T10:15:00Z',
  },
  {
    id: 'cust-2',
    customerCode: 'CUST-1002',
    name: 'Dilshan Silva',
    companyName: 'TimberCraft Interiors',
    email: 'dilshan@timbercraft.lk',
    phone: '+94 71 987 6543',
    address: 'Industrial Zone, Moratuwa',
    notes: 'Requires precision 3D CNC carving on Mahogany & Teak panels.',
    totalJobsCount: 14,
    totalSpentLKR: 540000,
    createdAt: '2026-02-15T11:20:00Z',
    updatedAt: '2026-08-05T14:40:00Z',
  },
  {
    id: 'cust-3',
    customerCode: 'CUST-1003',
    name: 'Nimesha Fernando',
    companyName: 'BioMed Design Tech',
    email: 'nimesha@biomed.lk',
    phone: '+94 76 555 4321',
    address: 'Technology Park, Pitipana, Homagama',
    notes: 'Medical device housing models. Requires high accuracy layer heights (0.12mm).',
    totalJobsCount: 4,
    totalSpentLKR: 92000,
    createdAt: '2026-04-02T09:10:00Z',
    updatedAt: '2026-07-28T16:00:00Z',
  },
  {
    id: 'cust-4',
    customerCode: 'CUST-1004',
    name: 'Ruwan Kumara',
    companyName: 'Individual Hardware Maker',
    email: 'ruwan.maker@gmail.com',
    phone: '+94 70 333 2211',
    address: 'Nugegoda',
    notes: 'Custom gear sets and mechanical brackets.',
    totalJobsCount: 2,
    totalSpentLKR: 18500,
    createdAt: '2026-06-18T14:00:00Z',
    updatedAt: '2026-08-07T09:30:00Z',
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-1',
    jobNumber: 'JOB-2026-0042',
    customerId: 'cust-1',
    customerName: 'Kasun Jayawardena (Apex Robotics)',
    customerPhone: '+94 77 123 4567',
    customerEmail: 'kasun@apexrobotics.lk',
    title: 'Autonomous Drone Chassis & Gimbal Enclosure',
    priority: 'URGENT',
    status: 'PRINTING',
    manufacturingTypes: ['3D_PRINTING'],
    parts: [
      {
        id: 'part-101',
        partName: 'Lower Drone Baseplate',
        quantity: 2,
        manufacturingMethod: '3D_PRINTING',
        unitPriceLKR: 8500,
        totalPriceLKR: 17000,
        printDetails: {
          printerId: 'mach-1',
          printerName: 'Bambu Lab X1-Carbon #01',
          materialId: 'mat-2',
          materialName: 'PETG Carbon Fiber',
          color: 'Matte Black',
          filamentWeightGrams: 320,
          estimatedPrintMinutes: 280,
          layerHeightMm: 0.20,
          infillPercentage: 40,
          hasSupports: true,
          nozzleSizeMm: 0.4,
          slicerFileUrl: 'drone_base_v3.3mf',
          gcodeFileUrl: 'drone_base_v3.gcode',
        },
        notes: 'High infill required for structural rigidity.',
      },
      {
        id: 'part-102',
        partName: 'Camera Gimbal Mount Hood',
        quantity: 4,
        manufacturingMethod: '3D_PRINTING',
        unitPriceLKR: 2500,
        totalPriceLKR: 10000,
        printDetails: {
          printerId: 'mach-2',
          printerName: 'Prusa MK4 #02',
          materialId: 'mat-1',
          materialName: 'PLA Tough',
          color: 'Signal Yellow',
          filamentWeightGrams: 85,
          estimatedPrintMinutes: 110,
          layerHeightMm: 0.15,
          infillPercentage: 25,
          hasSupports: false,
          nozzleSizeMm: 0.4,
        },
      },
    ],
    subtotalLKR: 27000,
    discountLKR: 2000,
    taxLKR: 0,
    deliveryFeeLKR: 1000,
    totalLKR: 26000,
    paidAmountLKR: 15000,
    balanceLKR: 11000,
    paymentStatus: 'PARTIALLY_PAID',
    dueDate: '2026-08-10',
    deliveryMethod: 'COURIER',
    deliveryAddress: 'No 45, Kandy Road, Malabe',
    notes: 'Urgent release for field testing prototype event.',
    createdAt: '2026-08-07T09:20:00Z',
    updatedAt: '2026-08-08T10:00:00Z',
  },
  {
    id: 'job-2',
    jobNumber: 'JOB-2026-0043',
    customerId: 'cust-2',
    customerName: 'Dilshan Silva (TimberCraft)',
    customerPhone: '+94 71 987 6543',
    customerEmail: 'dilshan@timbercraft.lk',
    title: 'Custom Carved Mahogany Wall Relief Panels',
    priority: 'HIGH',
    status: 'CNC_PROCESSING',
    manufacturingTypes: ['CNC'],
    parts: [
      {
        id: 'part-201',
        partName: 'Main Traditional Motif Panel (600x400mm)',
        quantity: 3,
        manufacturingMethod: 'CNC',
        unitPriceLKR: 35000,
        totalPriceLKR: 105000,
        cncDetails: {
          machineId: 'mach-3',
          machineName: 'RouterMax 1325 CNC Heavy Duty',
          woodType: 'Mahogany Hardwood',
          thicknessMm: 25,
          lengthMm: 600,
          widthMm: 400,
          toolDiameterMm: 6,
          feedRate: 2400,
          spindleSpeedRpm: 18000,
          estimatedMachiningMinutes: 190,
          camFileUrl: 'panel_carving_v2.dxf',
          gcodeFileUrl: 'panel_carving_v2.nc',
          finishingNotes: 'Deep 3D V-carve with ballnose 3mm pass.',
          materialCostLKR: 12000,
        },
      },
    ],
    subtotalLKR: 105000,
    discountLKR: 5000,
    taxLKR: 0,
    deliveryFeeLKR: 2500,
    totalLKR: 102500,
    paidAmountLKR: 50000,
    balanceLKR: 52500,
    paymentStatus: 'PARTIALLY_PAID',
    dueDate: '2026-08-12',
    deliveryMethod: 'DELIVERY',
    deliveryAddress: 'Hotel Site, Galle Road, Bentota',
    notes: 'Client will inspect wood grain before final polyurethane clear coat.',
    createdAt: '2026-08-06T11:15:00Z',
    updatedAt: '2026-08-08T08:30:00Z',
  },
  {
    id: 'job-3',
    jobNumber: 'JOB-2026-0044',
    customerId: 'cust-3',
    customerName: 'Nimesha Fernando (BioMed)',
    customerPhone: '+94 76 555 4321',
    customerEmail: 'nimesha@biomed.lk',
    title: 'Precision Micro-Fluidic Testing Jig',
    priority: 'NORMAL',
    status: 'QUALITY_CHECK',
    manufacturingTypes: ['3D_PRINTING', 'CNC'],
    parts: [
      {
        id: 'part-301',
        partName: 'Acrylic CNC Top Plate',
        quantity: 1,
        manufacturingMethod: 'CNC',
        unitPriceLKR: 12000,
        totalPriceLKR: 12000,
        cncDetails: {
          machineId: 'mach-4',
          machineName: 'StepCraft D.840 Precision Desktop',
          woodType: 'Cast Clear Acrylic 10mm',
          thicknessMm: 10,
          lengthMm: 200,
          widthMm: 150,
          toolDiameterMm: 2,
          feedRate: 800,
          spindleSpeedRpm: 20000,
          estimatedMachiningMinutes: 45,
          materialCostLKR: 3500,
        },
      },
      {
        id: 'part-302',
        partName: 'Fluid Reservoir Base',
        quantity: 2,
        manufacturingMethod: '3D_PRINTING',
        unitPriceLKR: 6500,
        totalPriceLKR: 13000,
        printDetails: {
          printerId: 'mach-1',
          printerName: 'Bambu Lab X1-Carbon #01',
          materialId: 'mat-3',
          materialName: 'ABS Translucent',
          color: 'Clear Natural',
          filamentWeightGrams: 140,
          estimatedPrintMinutes: 160,
          layerHeightMm: 0.12,
          infillPercentage: 100,
          hasSupports: false,
          nozzleSizeMm: 0.4,
        },
      },
    ],
    subtotalLKR: 25000,
    discountLKR: 0,
    taxLKR: 0,
    deliveryFeeLKR: 0,
    totalLKR: 25000,
    paidAmountLKR: 25000,
    balanceLKR: 0,
    paymentStatus: 'PAID',
    dueDate: '2026-08-09',
    deliveryMethod: 'PICKUP',
    notes: 'Water tightness check required.',
    createdAt: '2026-08-04T14:30:00Z',
    updatedAt: '2026-08-08T11:20:00Z',
  },
  {
    id: 'job-4',
    jobNumber: 'JOB-2026-0045',
    customerId: 'cust-4',
    customerName: 'Ruwan Kumara',
    customerPhone: '+94 70 333 2211',
    customerEmail: 'ruwan.maker@gmail.com',
    title: 'Helical Drive Gear Replacement Assembly',
    priority: 'NORMAL',
    status: 'READY',
    manufacturingTypes: ['3D_PRINTING'],
    parts: [
      {
        id: 'part-401',
        partName: 'Nylon/ASA Helical Gear (Z=42)',
        quantity: 5,
        manufacturingMethod: '3D_PRINTING',
        unitPriceLKR: 1800,
        totalPriceLKR: 9000,
        printDetails: {
          printerId: 'mach-2',
          printerName: 'Prusa MK4 #02',
          materialId: 'mat-5',
          materialName: 'ASA Heavy Duty',
          color: 'Black',
          filamentWeightGrams: 90,
          estimatedPrintMinutes: 120,
          layerHeightMm: 0.16,
          infillPercentage: 80,
          hasSupports: true,
          nozzleSizeMm: 0.4,
        },
      },
    ],
    subtotalLKR: 9000,
    discountLKR: 0,
    taxLKR: 0,
    deliveryFeeLKR: 500,
    totalLKR: 9500,
    paidAmountLKR: 9500,
    balanceLKR: 0,
    paymentStatus: 'PAID',
    dueDate: '2026-08-08',
    deliveryMethod: 'PICKUP',
    notes: 'Ready for customer pickup at shop.',
    createdAt: '2026-08-05T08:00:00Z',
    updatedAt: '2026-08-08T12:00:00Z',
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-1',
    name: 'eSUN PLA+ Filament',
    type: '3D_PRINTING',
    category: 'PLA',
    color: 'Signal Yellow',
    brand: 'eSUN',
    supplier: '3D Print LK',
    unit: 'grams',
    currentStockQuantity: 3400,
    minStockThreshold: 1000,
    unitCostLKR: 9.5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
  },
  {
    id: 'mat-2',
    name: 'Bambu Lab PETG-CF',
    type: '3D_PRINTING',
    category: 'PETG',
    color: 'Matte Black',
    brand: 'Bambu Lab',
    supplier: 'TechStore LK',
    unit: 'grams',
    currentStockQuantity: 850,
    minStockThreshold: 1000,
    unitCostLKR: 24,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
  },
  {
    id: 'mat-3',
    name: 'Polymaker PolyLite ABS',
    type: '3D_PRINTING',
    category: 'ABS',
    color: 'Clear Natural',
    brand: 'Polymaker',
    supplier: '3D Print LK',
    unit: 'grams',
    currentStockQuantity: 2100,
    minStockThreshold: 800,
    unitCostLKR: 14,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
  },
  {
    id: 'mat-4',
    name: 'Mahogany Hardwood Boards (25mm)',
    type: 'CNC',
    category: 'MAHOGANY',
    color: 'Natural Reddish Brown',
    brand: 'Local Sawmill',
    supplier: 'State Timber Corp',
    unit: 'board_feet',
    currentStockQuantity: 180,
    minStockThreshold: 50,
    unitCostLKR: 850,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
  },
  {
    id: 'mat-5',
    name: 'Commercial Grade Plywood (18mm 8x4ft)',
    type: 'CNC',
    category: 'PLYWOOD',
    color: 'Birch Veneer',
    brand: 'Sinha Plywood',
    supplier: 'Hardware Mart',
    unit: 'sheets',
    currentStockQuantity: 12,
    minStockThreshold: 15,
    unitCostLKR: 9200,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
  },
];

export const INITIAL_MACHINES: Machine[] = [
  {
    id: 'mach-1',
    name: 'Bambu Lab X1-Carbon #01',
    type: '3D_PRINTER',
    model: 'X1C Combo AMS',
    status: 'RUNNING',
    currentJobId: 'job-1',
    currentJobTitle: 'JOB-2026-0042 (Drone Chassis Base)',
    totalOperatingMinutes: 14200,
    lastMaintenanceDate: '2026-07-20',
    nextMaintenanceDate: '2026-08-20',
    notes: '0.4mm Hardened Steel Nozzle installed.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T10:00:00Z',
  },
  {
    id: 'mach-2',
    name: 'Prusa MK4 #02',
    type: '3D_PRINTER',
    model: 'Prusa MK4 Enclosed',
    status: 'IDLE',
    currentJobId: null,
    totalOperatingMinutes: 9800,
    lastMaintenanceDate: '2026-07-25',
    nextMaintenanceDate: '2026-08-25',
    notes: 'Next-step belt tension check due.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T12:00:00Z',
  },
  {
    id: 'mach-3',
    name: 'RouterMax 1325 CNC Heavy Duty',
    type: 'CNC_ROUTER',
    model: '1325 3-Axis 4.5kW Spindle',
    status: 'RUNNING',
    currentJobId: 'job-2',
    currentJobTitle: 'JOB-2026-0043 (Mahogany Wall Panels)',
    totalOperatingMinutes: 28500,
    lastMaintenanceDate: '2026-07-15',
    nextMaintenanceDate: '2026-08-15',
    notes: 'Vacuum bed pump serviced.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T08:30:00Z',
  },
  {
    id: 'mach-4',
    name: 'StepCraft D.840 Precision CNC',
    type: 'CNC_ROUTER',
    model: 'D.840 High Speed Spindle',
    status: 'IDLE',
    currentJobId: null,
    totalOperatingMinutes: 4500,
    lastMaintenanceDate: '2026-08-01',
    nextMaintenanceDate: '2026-09-01',
    notes: 'Ideal for small precision plastic and brass milling.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-08T11:20:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    paymentNumber: 'PAY-1001',
    jobId: 'job-1',
    jobTitle: 'JOB-2026-0042 (Drone Chassis)',
    customerId: 'cust-1',
    customerName: 'Kasun Jayawardena',
    amountLKR: 15000,
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'BT-998822-HNB',
    notes: 'Advance deposit for 3D printing job.',
    recordedBy: 'usr-1',
    recordedByName: 'Admin Operator',
    recordedAt: '2026-08-07T10:00:00Z',
    createdAt: '2026-08-07T10:00:00Z',
  },
  {
    id: 'pay-2',
    paymentNumber: 'PAY-1002',
    jobId: 'job-2',
    jobTitle: 'JOB-2026-0043 (Mahogany Panels)',
    customerId: 'cust-2',
    customerName: 'Dilshan Silva',
    amountLKR: 50000,
    paymentMethod: 'ONLINE',
    referenceNumber: 'PAY-ONL-88231',
    notes: '50% upfront payment for wood stock and CNC machining.',
    recordedBy: 'usr-1',
    recordedByName: 'Admin Operator',
    recordedAt: '2026-08-06T12:00:00Z',
    createdAt: '2026-08-06T12:00:00Z',
  },
  {
    id: 'pay-3',
    paymentNumber: 'PAY-1003',
    jobId: 'job-3',
    jobTitle: 'JOB-2026-0044 (Micro-Fluidic Jig)',
    customerId: 'cust-3',
    customerName: 'Nimesha Fernando',
    amountLKR: 25000,
    paymentMethod: 'CASH',
    referenceNumber: 'CASH-REC-0012',
    notes: 'Full payment received upon order confirmation.',
    recordedBy: 'usr-1',
    recordedByName: 'Admin Operator',
    recordedAt: '2026-08-04T15:00:00Z',
    createdAt: '2026-08-04T15:00:00Z',
  },
];
