import { z } from 'zod';

export const jobPartSchema = z.object({
  id: z.string(),
  partName: z.string().min(1, 'Part name is required'),
  quantity: z.number().int().min(1, 'Quantity must be at least 1'),
  manufacturingMethod: z.enum(['3D_PRINTING', 'CNC']),
  unitPriceLKR: z.number().min(0, 'Unit price must be positive'),
  totalPriceLKR: z.number().min(0),
  printDetails: z.object({
    printerId: z.string().optional(),
    printerName: z.string().optional(),
    materialId: z.string().optional(),
    materialName: z.string().optional(),
    color: z.string().optional(),
    filamentWeightGrams: z.number().min(0),
    estimatedPrintMinutes: z.number().min(0),
    layerHeightMm: z.number().optional(),
    infillPercentage: z.number().optional(),
    hasSupports: z.boolean().optional(),
    nozzleSizeMm: z.number().optional(),
    slicerFileUrl: z.string().optional(),
    gcodeFileUrl: z.string().optional(),
  }).optional(),
  cncDetails: z.object({
    machineId: z.string().optional(),
    machineName: z.string().optional(),
    woodType: z.string().optional(),
    thicknessMm: z.number().min(0),
    lengthMm: z.number().min(0),
    widthMm: z.number().min(0),
    toolDiameterMm: z.number().optional(),
    feedRate: z.number().optional(),
    spindleSpeedRpm: z.number().optional(),
    estimatedMachiningMinutes: z.number().min(0),
    camFileUrl: z.string().optional(),
    gcodeFileUrl: z.string().optional(),
    finishingNotes: z.string().optional(),
    materialCostLKR: z.number().min(0),
  }).optional(),
  notes: z.string().optional(),
});

export const jobSchema = z.object({
  customerId: z.string().min(1, 'Please select a customer'),
  customerName: z.string().min(1, 'Customer name required'),
  customerPhone: z.string().optional(),
  customerEmail: z.string().optional(),
  title: z.string().min(3, 'Job title must be at least 3 characters'),
  priority: z.enum(['LOW', 'NORMAL', 'HIGH', 'URGENT']),
  status: z.enum([
    'QUOTATION',
    'ORDER_CONFIRMED',
    'TO_BE_PRINTED',
    'PRINTING',
    'CNC_PROCESSING',
    'FINISHING',
    'QUALITY_CHECK',
    'READY',
    'DELIVERED',
    'COMPLETED',
    'CANCELLED'
  ]),
  manufacturingTypes: z.array(z.enum(['3D_PRINTING', 'CNC'])).min(1, 'Select at least one manufacturing method'),
  parts: z.array(jobPartSchema).min(1, 'At least one part is required'),
  discountLKR: z.number().min(0).default(0),
  taxLKR: z.number().min(0).default(0),
  deliveryFeeLKR: z.number().min(0).default(0),
  dueDate: z.string().min(1, 'Due date is required'),
  deliveryMethod: z.enum(['PICKUP', 'COURIER', 'DELIVERY']),
  deliveryAddress: z.string().optional(),
  notes: z.string().optional(),
});

export type JobFormValues = z.infer<typeof jobSchema>;
